export const workList = [
  {
    title: 'No-Kill Policy - The New Paradise for Homeless Animals?',
    alt: 'animal-protection',
    link: 'https://www.twreporter.org/a/eng-animal-protection',
    image: '/static/thereporter/animal-protection.gif',
    imgSize: {
      width: 640,
      height: 378,
    },
    organization: 'The Reporter Taiwan',
    month: 11,
    year: 2016,
  },
  {
    title: '[Chinese] The Predicament of the Perservation of Taiwanese Films (台灣電影的「陰濕路」)',
    alt: 'film-center',
    link: 'https://www.twreporter.org/i/film-center',
    image: '/static/thereporter/film-center.jpg',
    imgSize: {
      width: 1200,
      height: 937,
    },
    organization: 'The Reporter Taiwan',
    month: 7,
    year: 2016,
  },
  {
    title: 'Before Departure: Taiwanese Dream of Indonesian Fishermen (離岸之前)',
    alt: 'photoessay-far-sea-fishing',
    link: 'https://www.twreporter.org/a/eng-photoessay-far-sea-fishing/',
    image: '/static/thereporter/photoessay-far-sea-fishing.gif',
    imgSize: {
      width: 640,
      height: 342,
    },
    organization: 'The Reporter Taiwan',
    month: 12,
    year: 2016,
  },
  {
    title: '[Chinese] Obstacles faced by same-sex parents who want to raise children (Jim的成家夢)',
    alt: 'homofamily-15cards',
    link: 'https://www.twreporter.org/i/homofamily-15cards',
    image: '/static/thereporter/homofamily-15cards.jpg',
    imgSize: {
      width: 1290,
      height: 786,
    },
    organization: 'The Reporter Taiwan',
    month: 5,
    year: 2016,
  },
  {
    title: '[Chinese] How did farmlands in Qishan become landfills? (旗山找「碴」當農地變成掩埋場)',
    alt: 'steel-slag',
    link: 'https://www.twreporter.org/i/steel-slag',
    image: '/static/thereporter/steel-slag.jpg',
    imgSize: {
      width: 1400,
      height: 785,
    },
    organization: 'The Reporter Taiwan',
    month: 4,
    year: 2016,
  },
  {
    title: '[Chinese] Newsgame: Grandmather Liu Enters into the Legislature - Part 1 (劉姥姥進立法院)',
    alt: '20160201',
    link: 'https://www.twreporter.org/i/new-mp/20160201/',
    image: '/static/thereporter/20160201.jpg',
    imgSize: {
      width: 1200,
      height: 739,
    },
    organization: 'The Reporter Taiwan',
    month: 2,
    year: 2016,
  },
  {
    title: '[Chinese] Newsgame: Grandmather Liu Enters into the Legislature - Part 2 (劉姥姥進立法院)',
    alt: '20160222',
    link: 'https://www.twreporter.org/i/legislative-committee/20160222/',
    image: '/static/thereporter/20160222.jpg',
    imgSize: {
      width: 1200,
      height: 739,
    },
    organization: 'The Reporter Taiwan',
    month: 2,
    year: 2016,
  },
]
