export const workList = [
  {
    title: 'No-Kill Policy - The New Paradise for Homeless Animals? (零安樂死政策 流浪動物的新天堂樂園？)',
    alt: 'animal-protection',
    link: 'https://www.twreporter.org/a/eng-animal-protection',
    image: '/static/thereporter/animal-protection.gif',
    imgSize: {
      width: 640,
      height: 378,
    },
    organization: 'The Reporter Taiwan',
    month: 11,
    year: 2016,
  },
  {
    title: '[Chinese] The Stagnation of Growth in the Minimum Wage of Taiwan (到了 2018 年才 22K！曾經凍漲十年的基本工資)',
    alt: 'min-wage-draft',
    link: 'https://www.twreporter.org/i/min-wage-draft',
    image: '/static/thereporter/min-wage-draft.gif',
    imgSize: {
      width: 640,
      height: 420,
    },
    organization: 'The Reporter Taiwan',
    month: 8,
    year: 2017,
  },
  {
    title: '[Chinese] Tracking Promises Related to Labor Policies Made by President Tsai (蔡英文勞動政策追蹤平台)',
    alt: 'tsai-tracker',
    link: 'https://tsai-tracker.twreporter.org/',
    image: '/static/thereporter/tsai-tracker.jpg',
    imgSize: {
      width: 1073,
      height: 1412,
    },
    organization: 'The Reporter Taiwan',
    month: 5,
    year: 2017,
  },
  {
    title: 'Before Departure: Taiwanese Dream of Indonesian Fishermen (離岸之前)',
    alt: 'photoessay-far-sea-fishing',
    link: 'https://www.twreporter.org/a/eng-photoessay-far-sea-fishing/',
    image: '/static/thereporter/photoessay-far-sea-fishing.gif',
    imgSize: {
      width: 640,
      height: 342,
    },
    organization: 'The Reporter Taiwan',
    month: 12,
    year: 2016,
  },
  {
    title: '[Chinese] The Predicament of the Perservation of Taiwanese Films (台灣電影的「陰濕路」)',
    alt: 'film-center',
    link: 'https://www.twreporter.org/i/film-center',
    image: '/static/thereporter/film-center.jpg',
    imgSize: {
      width: 1200,
      height: 937,
    },
    organization: 'The Reporter Taiwan',
    month: 7,
    year: 2016,
  },
  {
    title: '[Chinese] Obstacles faced by same-sex parents who want to raise children (Jim的成家夢)',
    alt: 'homofamily-15cards',
    link: 'https://www.twreporter.org/i/homofamily-15cards',
    image: '/static/thereporter/homofamily-15cards.jpg',
    imgSize: {
      width: 1290,
      height: 690,
    },
    organization: 'The Reporter Taiwan',
    month: 5,
    year: 2016,
  },
  {
    title: '[Chinese] How did farmlands in Qishan become landfills? (旗山找「碴」當農地變成掩埋場)',
    alt: 'steel-slag',
    link: 'https://www.twreporter.org/i/steel-slag',
    image: '/static/thereporter/steel-slag.jpg',
    imgSize: {
      width: 1400,
      height: 785,
    },
    organization: 'The Reporter Taiwan',
    month: 4,
    year: 2016,
  },
  {
    title: '[Chinese] Newsgame: Grandmather Liu Enters into the Legislature - Part 1 (劉姥姥進立法院)',
    alt: '20160201',
    link: 'https://www.twreporter.org/i/new-mp/20160201/',
    image: '/static/thereporter/20160201.jpg',
    imgSize: {
      width: 1200,
      height: 739,
    },
    organization: 'The Reporter Taiwan',
    month: 2,
    year: 2016,
  },
  {
    title: '[Chinese] Newsgame: Grandmather Liu Enters into the Legislature - Part 2 (劉姥姥進立法院)',
    alt: '20160222',
    link: 'https://www.twreporter.org/i/legislative-committee/20160222/',
    image: '/static/thereporter/20160222.jpg',
    imgSize: {
      width: 1200,
      height: 554,
    },
    organization: 'The Reporter Taiwan',
    month: 2,
    year: 2016,
  },
]

export const volunteerList = [
  {
    title: '[Chinese] 2016 Taiwan Election Dashboard: Candidates Who Pledge to Support Marriage Equality',
    alt: 'election2016',
    link: 'http://election2016.tapcpr.org/',
    image: '/static/tapcpr/election2016.jpg',
    imgSize: {
      width: 1200,
      height: 1643,
    },
    organization: 'TAPCPR',
    month: 12,
    year: 2015,
  },
  {
    title: '[Chinese] Official Website of Taiwan Alliance to Promote Civil Partnership Rights (TAPCPR)',
    alt: 'tapcpr',
    link: 'https://tapcpr.org/',
    image: '/static/tapcpr/tapcpr.jpg',
    imgSize: {
      width: 1200,
      height: 690,
    },
    organization: 'TAPCPR',
    month: 6,
    year: 2015,
  },
  {
    title: '[Chinese] KissMarriageEquality.org: Official Website for "Marriage Equality Revolution Front"',
    alt: 'kissmarriageequality',
    link: 'http://kissmarriageequality.org/',
    image: '/static/tapcpr/kissmarriageequality.jpg',
    imgSize: {
      width: 1401,
      height: 1230,
    },
    organization: 'TAPCPR',
    month: 10,
    year: 2014,
  },
  {
    title: '[Chinese] PinkDot TW: Official Website of PinkDot Taiwan',
    alt: 'pinkdottw',
    link: 'http://pinkdottw.berryvoice.org/',
    image: '/static/tapcpr/pinkdottw.jpg',
    imgSize: {
      width: 1200,
      height: 699,
    },
    organization: 'Pinkdot TW',
    month: 5,
    year: 2015,
  },
]
